### ISSUE TITLE
Set "max duration" for zones in device config

### ISSUE THREAD

**Issue by jheddings** [IndigoDomotics/rachio-indigo#10]
It would be nice to set the maximum zone duration in the plugin settings.  Occasionally, there are issues that prevent Indigo from stopping the current zone when running a schedule.  In those cases, being able to limit the max duration (in minutes?) would help avoid running for a VERY long time.

**Comment by FlyingDiver** [comment]
Please explain the circumstances "that prevent Indigo from stopping the current zone when running a schedule".

**Comment by jheddings** [comment]
> Please explain the circumstances "that prevent Indigo from stopping the current zone when running a schedule".

Typically when something goes sideways on the system running Indigo server:

1. Internet connectivity issue
2. macOS decides to go to sleep
3. System crash

In some cases, I've been away from home when these events happen.  It ends up running for a long period of time.

**Comment by FlyingDiver** [comment]
In all of those cases, the plugin won't be able to do anything either.

**Comment by jheddings** [comment]
Is there no option in the API to run for a duration when starting the zone?  My thought was to send the "start zone" command with a duration, which could be dialed back by the user.  I'm not familiar with the API, so this may not be the right answer.

**Comment by indigodomo** [comment]
When I first built the plugin, there was no such option. In the Rachio app, you can set the max duration for each zone, so what I did was to set it in there to the largest amount of time I would ever want a zone to run. That would act as the failsafe.

I haven't looked at the API in years so it may have more features in it now.

**Comment by FlyingDiver** [comment]
I think they took the max time out of the zone parameters.  I can't find it in either the iOS app or the website interface.

**Comment by FlyingDiver** [comment]
The plugin is sending the default max of 10800 (3 hrs) when it starts a zone.  If the servers are not honoring that, then it's out of our hands.  

@jheddings - when you had an issue, did it run longer than 3 hours (each zone)?

**Comment by indigodomo** [comment]
LOL, I guess I was misremembering. Maybe they updated it later and I did as well. Since I haven't used the plugin in well over a year I suppose my goldfish memory kicked in...

I do recall seeing it in one of the UI interfaces at one point.

**Comment by jheddings** [comment]
I'd have to spend time on it, but I _think_ it was longer than 3 hours.  I didn't realize that it was just "on/off" basically for API control.  That's a bummer for sure.

Thanks for looking into it!

**Comment by FlyingDiver** [comment]
The parameter is there in the API, but I have no idea if they actually honor it.  If you want to experiment, find this line in plugin.py and change the value:
`RACHIO_MAX_ZONE_DURATION        = 10800
`
If it does work, I can make it adjustable in the plugin configuration.

**Comment by jheddings** [comment]
Finally had the chance to check into this…  It does appear that changing this constant affects the zone duration.  By setting it to a low value (e.g. 5 seconds), I was able to start the zone in Indigo and see it shut off quickly visually, but no changes in Indigo.

**Comment by FlyingDiver** [comment]
Are you polling the Rachio servers or using the webhooks?  If you're polling, the change won't be seen until the next poll interval.

**Comment by jheddings** [comment]
I only changed the constant in the plugin to a small value…  I was not looking for a change in Indigo, just confirmation that the server was using the max duration parameter (which it appears did work).

-jh

**Comment by FlyingDiver** [comment]
OK, then next version I'll expose that value in the plugin config or somewhere useful.

**Comment by jheddings** [comment]
Thanks, Joe!

**Comment by FlyingDiver** [comment]
Implemented in 2022.0.1
