### ISSUE TITLE
Share Webhooks

### ISSUE THREAD

**Issue by mlamoure** [IndigoDomotics/rachio-indigo#12]
More of a discussion before it's even a proposed enhancement.

@FlyingDiver - do you use Homebridge?

My use case is such that I let Rachio control its own schedule.  I do not schedule from Indigo.  For manual starts, I prefer to use the Home app, so I'm interested in using this Homebridge plugin: https://github.com/valiquette/Homebridge-Rachio-Irrigation#readme

Problem is, Rachio will block the multiple plugin connections.  It's been a while since I tried, but I believe that is the case.

I only use Rachio status in Indigo for a few minor behaviors.  If I had to choose between the two plugins, I would choose to disable Indigo.

I think a potential resolution would be to share webhooks, where both plugins could get the messages simultaneously.  The Homebridge plugin supports something called Webhook Relay, which I have never used.

Any thoughts?

**Comment by FlyingDiver** [comment]
You can disable then webhook in the Indigo plug-in, and use polling for status updates, which would solve the immediate problem.

**Comment by FlyingDiver** [comment]
If you're only using the homebridge plug-in to initiate actions for Rachio, you could probably do that with the home link Siri plug-in and not use homebridge at all.

**Comment by FlyingDiver** [comment]
Lastly it's probably possible to use the homebridge relay functionality but that would take some research to figure out how it's done.

**Comment by mlamoure** [comment]
> If you're only using the homebridge plug-in to initiate actions for Rachio, you could probably do that with the home link Siri plug-in and not use homebridge at all.

I like the idea of this but I think Home Link Siri needs some improvements with regards to irrigation.  When you expose Rachio via it, you get a single irrigation switch, no breakdown of zones.  The Homebridge plugin is much more thorough in exposing / mapping your irrigation zones to HomeKit.



> You can disable then webhook in the Indigo plug-in, and use polling for status updates, which would solve the immediate problem.

Yes, my current setup.  Triggers are delayed due to polling.

**Comment by FlyingDiver** [comment]
If you have a link to the docs for the Webhook Relay, please provide it.

**Comment by mlamoure** [comment]
This is the link the plugin provided: 

https://webhookrelay.com/

Signup: 
https://my.webhookrelay.com/login

**Comment by FlyingDiver** [comment]
That's not very useful.  Where's the docs for the plugin that uses it?

**Comment by FlyingDiver** [comment]
Never mind.  I figured out what they meant.

**Comment by FlyingDiver** [comment]
OK, so the Webhook Relay service could be used to distribute the webhooks to both Homebridge and Indigo.  No changes are required in the Indigo plugin, you just need to uncheck "use Webhooks" in the config.  You'll need to set up the relay service, and use the URL that that plugin prints to the log (when webhooks are enabled) in the relay service.

But you would still need to enable webhooks in general, presumably from the Homebridge plugin, but using the relay service URL instead of the Homebridge one.  The trick is going to be enabling the Rachio webhooks with the URL specific to the relay service.

**Comment by mlamoure** [comment]
Thanks for spending time on this.

Maybe I’m confusing myself.

The Indigo Rachio plugin registers the Webhook via the API call: public/notification/webhook
I presume the Homebridge plugin does the same, so the two are competing on this activity, both overwriting the destination for Rachio to send events to.

I have the Homebridge plugin using the Webhook Relay successfully.  I think the flow is like this:

Rachio -> Webhook Relay Service -> Webhook Relay Agent (on my local network)

Here’s where I am unclear: The Homebridge plugin gets the messages from the Relay Agent, but the delivery method I’m unclear on.  Is it pushed via the Homebridge plugin subscribing to the Agent?  Is it polled?  The docs dont make it super clear: https://docs.webhookrelay.com/quick-start-forwarding

Coming back to Indigo Plugin, I think some modification to override were the plugin received the payloads from.  The plugin payloads will not come from the Indigo Reflector, but from the Relay Agent.  Second, an option to disable registering the webhook with Rachio.  But it’s making me nervous that I don’t understand the final delivery path between the Agent and the plugins.

**Comment by FlyingDiver** [comment]
First, webhooks are always pushed from the server (Rachio) to the client (Indigo or Homebridge plugin, usually, or Webhook Relay in this case).

The agent is not required.  That's only needed if the client can't receive the webhook call directly, like if it's not on a public IP.  The Indigo plugin uses the reflector to get around this.  I have no idea how Homebridge does it.  I guess it's using the Webhook Relay agent?  So Rachio pushes it to the WRS server, which sends it to the WRA (through a tunnel), which pushes it to the Homebridge plugin.

The Indigo plugin doesn't care WHERE the webhook is coming from, as long as the source uses the correct URL (which I mentioned earlier).  That can be easily configured in the WRS setup.  There's already a control in the plugin config to prevent the plugin from doing the setup.  But it doesn't use that control if it receives a webhook command.

**Comment by FlyingDiver** [comment]
So, if you already have the WRS set up to send to Homebridge, and Homebridge is subscribing to the webhooks you want, then all you should need to do is add the Indigo URL to the list of recipients in the WRS dashboard.  And then make sure that the "use webhooks" control is unchecked in the plugin config dialog.

**Comment by mlamoure** [comment]
I’m following you.

I added this to my WRS: https://< MY USERNAME >.indigodomo.net/message/com.indigodomo.opensource.rachio/webhook?api_key=< MY API KEY>

It looks like I’m getting an error: You are not authorized to access that resource

**Comment by FlyingDiver** [comment]
Where are you seeing that error?  Which server is generating it?  Are you seeing any errors in the Indigo log (indicating that Indigo is rejecting the request)?

**Comment by mlamoure** [comment]
The WRS Service Dashboard is showing that error for a failed message delivery to the Indigo endpoint I entered.  So, the Indigo Reflector server is producing that error.

**Comment by mlamoure** [comment]
I do not see any logs in the Indigo Log.

**Comment by FlyingDiver** [comment]
When I try to use the URL using curl in a Terminal window, I get the same error.  Something weird is going on, but I don't have time to look into it right now.

**Comment by FlyingDiver** [comment]
I had to update my Indigo access token, but then I was able to use the webhook URL.

I'm not sure there's anything for me to do here in this plugin.  You should be able to use that Relay Service without any changes to the plugin.

**Comment by mlamoure** [comment]
I was able to get it to work as well after rotating my API key.  Thanks for the help.
