### ISSUE TITLE
T# Forecast High High in UI

### ISSUE THREAD

**Issue by CommanderB** [IndigoDomotics/rachio-indigo#14]
When selecting a t#forecast_temperatureMin/Max through the UI, both Min and Max are displayed as High. The first one resolves to Min

![image](https://user-images.githubusercontent.com/18680188/208254923-437afac1-56a2-4d0c-a451-6ee217bd7ad8.png)

**Comment by FlyingDiver** [comment]
Cut and paste error in control page labels by whoever wrote this originally (wasn't me).  I fixed my copy of the code, it'll get released eventually.

**Comment by FlyingDiver** [comment]
Fixed in 2022.02.
