### ISSUE TITLE
"id" state causes SQL Logger plugin to fail

### ISSUE THREAD

**Issue by indigodomo** [IndigoDomotics/rachio-indigo#2]
The SQL Logger plugin uses state names directly as column names, which can cause a column name conflict if the state name is "id". Should be fixed in the sql logger plugin, but a faster turnaround is likely to be a fix in this plugin.

**Comment by indigodomo** [comment]
The fix should migrate any existing Indigo devices that have the "id" state to the new name (not just change the state name and break all existing devices).

**Comment by mbendiksen** [comment]
I think I have this fixed in SQL Logger plugin now. You can give it a try here: http://cloud.goprism.com/download/SQLLogger.zip
