### ISSUE TITLE
Implement webhooks for status

### ISSUE THREAD

**Issue by indigodomo** [IndigoDomotics/rachio-indigo#4]
The Rachio API supports webhooks to receive status updates. Our current architecture makes accepting connections from some _outside_ source difficult. The IWS rewrite that we're working on now will make that better (possibly significantly better) so we're just going to table doing it for now.

If Rachio becomes even more draconian when throttling API calls then we may have to re-evaluate.

**Comment by FlyingDiver** [comment]
I could probably do it with the recent enhancement I made to the HTTPd plugin.  It would require both plugins to be running.  Is that of interest?

**Comment by FlyingDiver** [comment]
Plugin uses Rachio API web hooks to update zone status starting with 2.0.1.  More work will be needed on this feature, but new issues should be opened as required.
