### ISSUE TITLE
water usage

### ISSUE THREAD

**Issue by farberm** [IndigoDomotics/rachio-indigo#8]
If I add a water meter to the Rachio Gen 2 will this report daily water usage in indigo

**Comment by FlyingDiver** [comment]
According the the Rachio website, the wireless water meter only works with Gen 3 systems.

And I can find no mention of the water meter in the API, so it appears that information is not available yet.  And once it's added to the API, then the plugin would have to be modified to provide the information.

So short answer - No.

**Comment by FlyingDiver** [comment]
I got a response on the Rachio forums, and the responder implied that the data was already there. As in, it's "estimated" if you don't have a flow meter and "actual" if you do.

As I don't currently have my Rachio (Gen 2) installed yet, I cannot confirm. I've asked for a clarification. Once I get that, I'll take a look at the code and see if it's possible to expose that information. I'll need some testers that actually have installed systems. Hopefully someone with a Gen 3 and the flow meter.

**Comment by FlyingDiver** [comment]
According to Rachio, water usage data is only available through the Webhooks interface.  If that gets implemented, then this enhancement can be as well.

**Comment by farberm** [comment]
Thats great news. I am waiting to hear if the system will receive input from a reed flow meter and it so then I will purchase the system and can help test.

**Comment by FlyingDiver** [comment]
In the web hook payload for a zone completed event, there is a data field:

    u'flowVolume': 0.0, 

So I could expose that info somehow.  What makes the most sense?
